# https://github.com/actions/runner-images/
name: System Info

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: pwsh

    steps:
      - uses: actions/checkout@v4

      - name: OS バージョンを表示
        shell: ${{ matrix.shell }}
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            lsb_release -a
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            sw_vers
          else
            Get-ComputerInfo | Select-Object WindowsProductName, WindowsVersion, OsArchitecture
          fi

      - name: CPU 詳細情報を表示
        shell: ${{ matrix.shell }}
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            lscpu
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            echo "Model: $(sysctl -n machdep.cpu.brand_string)"
            echo "Architecture: $(uname -m)"
            echo "Physical Cores: $(sysctl -n hw.physicalcpu)"
            echo "Logical Cores: $(sysctl -n hw.logicalcpu)"
            MAX_FREQ_HZ=$(sysctl -n hw.cpufrequency_max 2>/dev/null)
            [[ -n "$MAX_FREQ_HZ" ]] && echo "Max Frequency: $((MAX_FREQ_HZ / 1000000)) MHz"
          else
            Get-CimInstance Win32_Processor | Format-List Name, Manufacturer, MaxClockSpeed, NumberOfCores, NumberOfLogicalProcessors, ArchitectureDescription, SocketDesignation, Caption
          fi

      - name: メモリ情報を表示
        shell: ${{ matrix.shell }}
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            free -h
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            top -l 1 -s 0 | grep PhysMem
          else
            $mem = Get-CimInstance Win32_OperatingSystem
            "Total: {0}GB" -f [math]::Round($mem.TotalVisibleMemorySize/1MB, 2)
            "Free: {0}GB" -f [math]::Round($mem.FreePhysicalMemory/1MB, 2)
          fi

      - name: ストレージ空き容量を表示
        shell: ${{ matrix.shell }}
        run: |
          if [[ "${{ runner.os }}" == "Linux" || "${{ runner.os }}" == "macOS" ]]; then
            df -h
          else
            Get-Volume | Where-Object DriveLetter | 
              Select-Object DriveLetter, FileSystemLabel, 
                @{Name="Size(GB)";Expression={[math]::Round($_.Size/1GB,2)}}, 
                @{Name="Free(GB)";Expression={[math]::Round($_.SizeRemaining/1GB,2)}} | 
              Format-Table
          fi

      - name: インストール済み開発ツールの確認
        shell: bash
        run: |
          # ツールチェック用関数
          check_tool() {
            local tool=$1
            local cmd=$2
            echo -n "$tool: "
            if command -v $tool &>/dev/null; then
              eval "$cmd" 2>/dev/null || echo "version check failed"
            else
              echo "not found"
            fi
          }

          # 主要言語ランタイム
          echo "=== Language Runtimes ==="
          check_tool node "node --version"
          check_tool python "python --version || python3 --version"
          check_tool ruby "ruby --version"
          check_tool java "java -version 2>&1 | head -1"
          check_tool go "go version"
          check_tool dotnet "dotnet --list-sdks | tail -1"
          check_tool php "php --version | head -1"
          check_tool perl "perl --version | head -2 | tail -1"
          check_tool lua "lua -v"
          check_tool deno "deno --version | head -1"
          check_tool bun "bun --version"
          
          # コンパイラ & ビルドツール
          echo -e "\n=== Compilers & Build Tools ==="
          check_tool gcc "gcc --version | head -1"
          check_tool g++ "g++ --version | head -1"
          check_tool clang "clang --version | head -1"
          check_tool cmake "cmake --version | head -1"
          check_tool make "make --version | head -1"
          check_tool msbuild "msbuild -version | head -1"
          check_tool cargo "cargo --version"
          check_tool rustc "rustc --version"
          check_tool vcpkg "vcpkg version"
          
          # パッケージマネージャー
          echo -e "\n=== Package Managers ==="
          check_tool npm "npm --version"
          check_tool yarn "yarn --version"
          check_tool pip "pip --version | head -1"
          check_tool gem "gem --version"
          check_tool mvn "mvn --version | head -1"
          check_tool gradle "gradle --version | head -1"
          check_tool conan "conan --version"
          
          # クラウド & コンテナ
          echo -e "\n=== Cloud & Container ==="
          check_tool docker "docker --version"
          check_tool kubectl "kubectl version --client --short"
          check_tool helm "helm version --short"
          check_tool aws "aws --version"
          check_tool az "az --version | head -1"
          check_tool gcloud "gcloud --version | head -1"
          
          # モバイル開発
          echo -e "\n=== Mobile Development ==="
          check_tool flutter "flutter --version | head -1"
          check_tool adb "adb --version | head -1"
          
          # データベース
          echo -e "\n=== Databases ==="
          check_tool psql "psql --version"
          check_tool mysql "mysql --version"
          check_tool sqlcmd "sqlcmd -?"
          
          # その他ツール
          echo -e "\n=== Utilities ==="
          check_tool git "git --version"
          check_tool curl "curl --version | head -1"
          check_tool wget "wget --version | head -1"
          check_tool jq "jq --version"
          check_tool openssl "openssl version"
          check_tool ssh "ssh -V"
          check_tool ffmpeg "ffmpeg -version | head -1"
          check_tool pandoc "pandoc --version | head -1"
          check_tool terraform "terraform version | head -1"
          check_tool packer "packer --version"
          check_tool ansible "ansible --version | head -1"
          
          # OS固有ツール
          echo -e "\n=== OS-Specific Tools ==="
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            check_tool xcodebuild "xcodebuild -version | head -1"
            check_tool pod "pod --version"
            check_tool brew "brew --version | head -1"
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            check_tool pwsh "pwsh --version"
            check_tool choco "choco --version"
            check_tool nuget "nuget help | head -2 | tail -1"
          fi

      - name: Android NDK バージョン確認
        shell: bash
        run: |
          if [[ -n "$ANDROID_NDK_HOME" ]]; then
            ndk_path="$ANDROID_NDK_HOME"
          elif [[ -n "$ANDROID_NDK_LATEST_HOME" ]]; then
            ndk_path="$ANDROID_NDK_LATEST_HOME"
          else
            ndk_path=""
          fi
          
          if [[ -n "$ndk_path" ]]; then
            echo "Android NDK Path: $ndk_path"
            if [[ -f "$ndk_path/source.properties" ]]; then
              grep "Pkg.Revision" "$ndk_path/source.properties"
            else
              echo "source.properties not found"
            fi
          else
            echo "Android NDK environment variables not set"
          fi

      - name: インストール済みVSエクステンション確認 (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $extensions = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -prerelease -format json | 
            ConvertFrom-Json | 
            ForEach-Object { 
              & "$($_.installationPath)\Common7\IDE\vsixinstaller.exe" /list | 
                Where-Object { $_ -match "Extension Name" } 
            }
          
          if ($extensions) {
            "Installed VS Extensions:"
            $extensions
          } else {
            "No VS extensions found"
          }
